apiVersion: sync.stangj.com/v1
kind: Secretsync
metadata:
  labels:
    app.kubernetes.io/name: secretsync-controller
    app.kubernetes.io/managed-by: kustomize
  name: secretsync-sample
spec:
  # TODO(user): Add fields here
